### ISSUE TITLE
its not an issue , its my question, I got only this thing to ask you

### ISSUE THREAD

**Issue by rabi-999** [pavankjadda/Angular-WebApp-ServiceNow#23]
I read your instruction on using and installing, I got one doubt.

There you have mentioned to create user and used the same user credentials to access api, this means for each call you use same user for calling rest and getting data.

Suppose if different users having access to angular portal or app. How different users login and get their related data.

Is this app covers authentication of each user. 

For ex : if user A logs in , that should show data related to him, his user account details, his assigned incidents etc.

As here in this we use only one user credentials  , is this possible.

Let me know , if this doesn't clear you , I wish to add more clarity . Please let me know if this is possible @pavankjadda

**Comment by rabi-999** [comment]
@pavankjadda

**Comment by pavankjadda** [comment]
> There you have mentioned to create user and used the same user credentials to access api, this means for each call you use same user for calling rest and getting data.

Not same user. User needs to pass on credentials for first time. After that ServiceNow issues OAuth 2.0 tokens `refresh_token ` and `access_token`

**Comment by rabi-999** [comment]
> > There you have mentioned to create user and used the same user credentials to access api, this means for each call you use same user for calling rest and getting data.
> 
> Not same user. User needs to pass on credentials for first time. After that ServiceNow issues OAuth 2.0 tokens `refresh_token ` and `access_token`

what if other user wants to log in to the system, its changes the credentials right.

"Make sure the user has REST API access and assigned snc_platform_rest_api_access role. If not refer to ServiceNow user guide and add role to the user."

according to above statement all users must have role who logs in correct.

let me know if I am understanding wrong . thanks for response  @pavankjadda
